sudo: required

services:
  - docker

before_install:
  - docker build -t mrx/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run mrx/react-test npm run test -- --coverage

after_success:
  - docker build -t mrx101/multi-client ./client
  - docker build -t mrx101/multi-nginx ./nginx
  - docker build -t mrx101/multi-server ./server
  - docker build -t mrx101/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push mrx101/multi-client:latest
  - docker push mrx101/multi-nginx:latest
  - docker push mrx101/multi-server:latest
  - docker push mrx101/multi-worker:latest