sudo: required

services:
  - docker

before_install:
  - docker build -t mrx/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run mrx/react-test npm run test -- --coverage

after_success:
  - docker build -t mrx/multi-client ./client
  - docker build -t mrx/multi-nginx ./nginx
  - docker build -t mrx/multi-server ./server
  - docker build -t mrx/multi-worker ./worker
